In [2]:
import numpy as np

In [31]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [32]:
arr1*arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [35]:
arr1**1.7

array([[  1.        ,   3.24900959,   6.47300784],
       [ 10.55606329,  15.42584657,  21.03086452]])

In [36]:
arr1 = np.arange(10)

In [37]:
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
arr1[5]

5

In [39]:
arr1[5:8]

array([5, 6, 7])

In [40]:
arr1[5:8] = 23

In [41]:
arr_1 = arr1[5:8]

In [42]:
arr_1[1] = 999

In [43]:
arr1

array([  0,   1,   2,   3,   4,  23, 999,  23,   8,   9])

In [44]:
arr_2 =arr1[5:8].copy()

In [48]:
arr_2[1] =0
arr_2

array([23,  0, 23])

In [49]:
arr1

array([  0,   1,   2,   3,   4,  23, 999,  23,   8,   9])

In [50]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2d[1]

array([4, 5, 6])

In [103]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],   [ [10,11,12],[13,14,15],[16,17,18]]])

In [104]:
old_values=arr3d[0].copy()

In [106]:
arr3d[0]= 42

In [107]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [108]:
arr3d[0] = old_values

In [110]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [114]:

arr1[1:6]

array([ 1,  2,  3,  4, 23])

In [115]:
arr1

array([  0,   1,   2,   3,   4,  23, 999,  23,   8,   9])

In [117]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
arr2d[:2,1:,]

array([[2, 3],
       [5, 6]])

In [123]:
arr2d[1,:2]

array([4, 5])

In [124]:
arr2d[2,:1]

array([7])

In [125]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [3]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [10]:
import random