In [9]:
import numpy as np

In [10]:
x = np.array([[1,2,3],[4,5,6]])

In [11]:
y = np.array([[6,23],[-1,7],[8,9]])

In [12]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [14]:
np.dot(x,np.ones(3))

array([  6.,  15.])

In [15]:
from numpy.linalg import inv,qr

In [17]:
X = np.random.randn(5,5)

In [18]:
X

array([[-0.11906151,  0.4509997 ,  1.10173088,  0.80892649, -0.0143223 ],
       [ 0.42657148,  0.83426318,  0.52999107,  0.22296674, -1.62552375],
       [ 0.86215921,  0.25629055, -0.01707744,  0.50267577, -1.93852455],
       [-0.06986318,  0.34937191,  1.36535702,  0.2516588 , -0.69131599],
       [ 0.29816931, -1.52353755,  0.1416366 , -0.06101157, -0.19302559]])

In [19]:
mat = X.T.dot(X)

In [20]:
mat

array([[ 1.03324318,  0.04445907,  0.02702536,  0.39641233, -2.37227041],
       [ 0.04445907,  3.408308  ,  1.19588425,  0.86054554, -1.80684413],
       [ 0.02702536,  1.19588425,  3.37925381,  1.33576791, -1.81541998],
       [ 0.39641233,  0.86054554,  1.33576791,  1.02381374, -1.51067171],
       [-2.37227041, -1.80684413, -1.81541998, -1.51067171,  6.9155867 ]])

In [21]:
mat.dot(inv(mat))

array([[  1.00000000e+00,  -2.27373675e-13,  -4.54747351e-13,
          9.09494702e-13,   0.00000000e+00],
       [  9.09494702e-13,   1.00000000e+00,  -2.27373675e-13,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.27373675e-13,  -4.54747351e-13],
       [  9.09494702e-13,   2.27373675e-13,   4.54747351e-13,
          1.00000000e+00,   4.54747351e-13],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00]])

In [22]:
q,r = qr(mat)

In [23]:
r

array([[ -2.61822614e+00,  -1.85516450e+00,  -1.91297426e+00,
         -1.70860841e+00,   7.48026137e+00],
       [  0.00000000e+00,  -3.68948075e+00,  -2.43913128e+00,
         -1.35219276e+00,   2.26401944e+00],
       [  0.00000000e+00,   0.00000000e+00,  -2.88468707e+00,
         -1.07363687e+00,   1.07480142e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -3.34390120e-01,  -2.45516609e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   2.24455610e-04]])

In [24]:
samples = np.random.normal(size=(4,4))

In [26]:
samples

array([[-0.31792775,  0.90154931, -1.37846722,  0.47144884],
       [ 0.54386564,  0.25643367,  1.95132376, -0.81371073],
       [-1.2770933 ,  1.20946819, -1.50249957,  0.18203036],
       [ 1.35151709, -0.62196062,  0.74884514,  0.2198709 ]])

In [27]:
from random import normalvariate#单次随机散步模拟

In [28]:
N = 1000000

In [35]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

1 loop, best of 3: 1.11 s per loop


In [36]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 39.5 ms per loop


In [43]:
import random
psoition = 0
walk = [psoition]
steps=1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    psoition+=step
    walk.append(psoition)

In [63]:
#多次随机散步模拟

In [64]:
nwalks = 5000

In [65]:
nsteps = 1000

In [66]:
draws = np.random.randint(0,2,size=(nwalks,nsteps))#0或1

In [67]:
steps = np.where(draws>0,1,-1)

In [75]:
walks = steps.cumsum(1)

In [76]:
walks

array([[  1,   2,   1, ..., -38, -37, -38],
       [ -1,  -2,  -3, ...,  24,  23,  22],
       [  1,   0,  -1, ...,  28,  29,  28],
       ..., 
       [  1,   0,  -1, ...,   8,   7,   8],
       [  1,   0,  -1, ...,  26,  25,  24],
       [  1,   0,  -1, ...,  12,  13,  12]], dtype=int32)

In [77]:
walks.max(),walks.min()

(113, -136)

In [78]:
hits30 = (np.abs(walks)>=30).any(1)#里面有任意一步走到30

In [79]:
hits30

array([ True,  True,  True, ...,  True, False,  True], dtype=bool)

In [80]:
hits30.sum()

3400

In [81]:
crossing_times = (np.abs(walks[hits30])>=30).argmax(1)

In [83]:
crossing_times.mean()

502.17823529411766

In [84]:
crossing_times

array([787, 209, 741, ..., 451, 295,  89], dtype=int64)