In [1]:
dicta={'name':'WE','age':25,'city':'LongDon'}

In [7]:
for key,aaa in dicta.items():
    print(key,aaa)

age 25
city LongDon
name WE


In [23]:
import numpy as np

In [33]:
a=np.array(['c',1,2])

In [34]:
type(a)

numpy.ndarray

In [35]:
a.dtype

dtype('<U1')

In [44]:
a.ndim,a.size,a.shape,a.itemsize,a.data

(1, 3, (3,), 4, <memory at 0x7fb71c3a5648>)

In [158]:
a=np.arange(0,12).reshape(3,4)

In [159]:
b=a[:2]

In [160]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [161]:
b[1][1]=10
a

array([[ 0,  1,  2,  3],
       [ 4, 10,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
np.linspace(1,20,6)

array([  1. ,   4.8,   8.6,  12.4,  16.2,  20. ])

In [80]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
b=np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [62]:
np.dot(a,a)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [74]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [77]:
a=[1,2,3,4,3,4,3,4,3,4,5,6,9]

In [97]:
A=np.random.randn(4,4)
A   

array([[ 0.00710807, -0.85426274,  0.01226521,  1.40458481],
       [-0.1220772 ,  1.52896413, -1.19048937,  1.17218645],
       [-1.30121845,  0.85313763,  0.92422552,  0.64055019],
       [-1.41723182,  0.22234656, -1.19819686, -0.0700827 ]])

In [93]:
a=np.random.random((4,4))
a

array([[ 0.20084782,  0.51710691,  0.72656457,  0.6733046 ],
       [ 0.63811285,  0.4404296 ,  0.9916141 ,  0.13101822],
       [ 0.35815522,  0.83934027,  0.08765159,  0.33488911],
       [ 0.13260332,  0.23369097,  0.11520015,  0.23113688]])

In [98]:
A<0.5

array([[ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True,  True,  True,  True]], dtype=bool)

In [101]:
A[A<0.5]

array([ 0.00710807, -0.85426274,  0.01226521, -0.1220772 , -1.19048937,
       -1.30121845, -1.41723182,  0.22234656, -1.19819686, -0.0700827 ])

In [103]:
A.shape=(2,8)

In [107]:
A=np.ones((3,3))
B=np.zeros((3,3))

In [112]:
np.vstack((A,B))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [114]:
np.hstack((A,B))

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.]])

In [115]:
a=np.array([0,1,2])
b=np.array([4,5,6])
c=np.array([7,8,9])

In [117]:
np.column_stack((a,b,c))

array([[0, 4, 7],
       [1, 5, 8],
       [2, 6, 9]])

In [118]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
A=np.arange(16).reshape(4,4)

In [124]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
[B,C]=np.hsplit(A,2)

In [126]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [127]:
[B,C]=np.vsplit(A,2)

In [128]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
[A1,A2,A3]=np.split(A,[1,2],axis=1)#指定列数为单列

In [137]:
A1,A2,A3

(array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [140]:
import pandas as pd

In [144]:
pd.read_table('/home/x/桌面/tt.txt',sep='\d*',header=None)#skiprows 跳过指定行

/root/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':
/root/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py:1728: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())
/root/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py:1730: FutureWarning: split() requires a non-empty pattern match.
  yield pat.split(line.strip())


0       1         2   3
0 NaN     enj       aaa NaN
1 NaN    jklj      aaaa NaN
2 NaN     jkl  fjdsajkl NaN
3 NaN  kjlkjl       jlj NaN

In [145]:
#read_csv('xxx.txt',skiprows=[2,3],nrows=3,header=None)  nrows：从该行开始往后读取