In [14]:
import numpy as np
import pandas as pd

In [15]:
data=np.genfromtxt('F:/linux/data.csv',delimiter=',',names=True)

In [16]:
data

array([(1.0, 123.0, 1.4, 23.0), (2.0, 110.0, 0.5, 18.0),
       (3.0, 164.0, 2.1, 19.0)], 
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [17]:
data['id']

array([ 1.,  2.,  3.])

In [21]:
s=pd.Series([12,-4,4,5,6],index=['a','b','c','d','e'])

In [22]:
s

a    12
b    -4
c     4
d     5
e     6
dtype: int64

In [25]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [27]:
s.values

array([12, -4,  4,  5,  6], dtype=int64)

In [50]:
serd=pd.Series([1,0,3,1,2,3],index=['w','w','b','g','g','y'])

In [51]:
serd.unique()

array([1, 0, 3, 2], dtype=int64)

In [52]:
serd.value_counts()

3    2
1    2
2    1
0    1
dtype: int64

In [53]:
serd[serd.isin([0,1])]

w    1
w    0
g    1
dtype: int64

In [54]:
s2=pd.Series([1,2,np.nan,np.nan,3,4,5])

In [58]:
s2[s2.notnull()]

0    1.0
1    2.0
4    3.0
5    4.0
6    5.0
dtype: float64

In [59]:
s2.notnull()

0     True
1     True
2    False
3    False
4     True
5     True
6     True
dtype: bool

In [72]:
data={'color':['blue','green','yellow','red','white'],'object':['ball','pen','pencil','paper','mug'],'price':[1.2,1.0,0.6,0.9,1.7]}

In [73]:
data

{'color': ['blue', 'green', 'yellow', 'red', 'white'],
 'object': ['ball', 'pen', 'pencil', 'paper', 'mug'],
 'price': [1.2, 1.0, 0.6, 0.9, 1.7]}

In [74]:
frame1=pd.DataFrame(data)

In [75]:
frame1

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [76]:
frame1=pd.DataFrame(data,columns=['color','object'])

In [77]:
frame1

color  object
0    blue    ball
1   green     pen
2  yellow  pencil
3     red   paper
4   white     mug

In [78]:
frame1.values

array([['blue', 'ball'],
       ['green', 'pen'],
       ['yellow', 'pencil'],
       ['red', 'paper'],
       ['white', 'mug']], dtype=object)

In [92]:
frame1.ix[[1,4]]

color object
1  green    pen
4  white    mug

In [88]:
frame1[1:2]

color object
1  green    pen

In [94]:
frame1['color'][2]

'yellow'

In [96]:
frame1.index.name='id';frame1.columns.name='item'

In [97]:
frame1

item   color  object
id                  
0       blue    ball
1      green     pen
2     yellow  pencil
3        red   paper
4      white     mug

In [98]:
frame1['new']=12

In [100]:
seq=np.arange(5)

In [108]:
frame1['new']=seq[::-1]

In [112]:
frame1[frame1.isin([1.0,'pen'])]

item color object  new
id                    
0      NaN    NaN  NaN
1      NaN    pen  NaN
2      NaN    NaN  NaN
3      NaN    NaN  1.0
4      NaN    NaN  NaN

In [113]:
del frame1['new']

In [114]:
frame1

item   color  object
id                  
0       blue    ball
1      green     pen
2     yellow  pencil
3        red   paper
4      white     mug

In [116]:
frame=pd.DataFrame(np.arange(16).reshape(4,4))

In [118]:
frame

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [124]:
ser3=pd.Series([1,5,6,3],index=[0,3,5,6])
ser3

0    1
3    5
5    6
6    3
dtype: int64

In [126]:
ser3.reindex(range(6),method='ffill')#向前填充

0    1
1    1
2    1
3    5
4    5
5    6
dtype: int64

In [127]:
ser3.reindex(range(6),method='bfill')#向后填充

0    1
1    5
2    5
3    5
4    6
5    6
dtype: int64

In [154]:
frame=pd.DataFrame(np.random.randn(16).reshape(4,4),index=['red','blue','yellow','white'],columns=['ball','pen','pencil','paper'])

In [155]:
frame

ball       pen    pencil     paper
red    -0.247339  0.062556  1.978081  0.386949
blue    2.308897  0.721517  0.376770  0.164867
yellow -0.598208  0.754422  1.160723  1.836295
white  -0.116154  1.200319 -1.426520  0.578937

In [156]:
frame.drop(['blue','yellow'])

ball       pen    pencil     paper
red   -0.247339  0.062556  1.978081  0.386949
white -0.116154  1.200319 -1.426520  0.578937

In [157]:
frame.drop(['ball','pen'],axis=1)

pencil     paper
red     1.978081  0.386949
blue    0.376770  0.164867
yellow  1.160723  1.836295
white  -1.426520  0.578937

In [158]:
frame

ball       pen    pencil     paper
red    -0.247339  0.062556  1.978081  0.386949
blue    2.308897  0.721517  0.376770  0.164867
yellow -0.598208  0.754422  1.160723  1.836295
white  -0.116154  1.200319 -1.426520  0.578937

In [159]:
def f(x):
    return x.max()+x.min()

In [160]:
frame.apply(f,axis=1)

red       1.730743
blue      2.473764
yellow    1.238087
white    -0.226201
dtype: float64

In [161]:
frame.describe()

ball       pen    pencil     paper
count  4.000000  4.000000  4.000000  4.000000
mean   0.336799  0.684703  0.522264  0.741762
std    1.330388  0.468737  1.454414  0.749047
min   -0.598208  0.062556 -1.426520  0.164867
25%   -0.335056  0.556777 -0.074053  0.331428
50%   -0.181747  0.737970  0.768746  0.482943
75%    0.490108  0.865896  1.365063  0.893277
max    2.308897  1.200319  1.978081  1.836295

In [162]:
frame.sum(axis=0)

ball      1.347195
pen       2.738814
pencil    2.089054
paper     2.967048
dtype: float64

In [163]:
serd=pd.Series([1,0,3,1,2,3],index=['w','w','b','g','g','y'])

In [164]:
serd.sort_index(ascending=False)

y    3
w    0
w    1
g    2
g    1
b    3
dtype: int64

In [166]:
frame.sort_index(by='pen')

d:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


ball       pen    pencil     paper
red    -0.247339  0.062556  1.978081  0.386949
blue    2.308897  0.721517  0.376770  0.164867
yellow -0.598208  0.754422  1.160723  1.836295
white  -0.116154  1.200319 -1.426520  0.578937

In [169]:
frame.rank(method='first',ascending=False)

ball  pen  pencil  paper
red      3.0  4.0     1.0    3.0
blue     1.0  3.0     3.0    4.0
yellow   4.0  2.0     2.0    1.0
white    2.0  1.0     4.0    2.0

In [170]:
ser=pd.Series([0,1,2,np.nan,9],index=['red','blue','yellow','white','green'])

In [171]:
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [172]:
ser['blue']=None

In [173]:
ser

red       0.0
blue      NaN
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [174]:
ser.dropna()

red       0.0
yellow    2.0
green     9.0
dtype: float64

In [175]:
ser

red       0.0
blue      NaN
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [176]:
ser[ser.notnull()]

red       0.0
yellow    2.0
green     9.0
dtype: float64

In [177]:
ser.fillna('a')

red       0
blue      a
yellow    2
white     a
green     9
dtype: object

In [179]:
mser=pd.Series(np.random.rand(8),index=[['w','w','w','b','b','r','r','r'],['u','d','r','u','d','u','d','l']])

In [180]:
mser

w  u    0.649504
   d    0.703475
   r    0.194305
b  u    0.648698
   d    0.580671
r  u    0.972230
   d    0.977760
   l    0.044782
dtype: float64

In [183]:
mser.index

MultiIndex(levels=[['b', 'r', 'w'], ['d', 'l', 'r', 'u']],
           labels=[[2, 2, 2, 0, 0, 1, 1, 1], [3, 0, 2, 3, 0, 3, 0, 1]])

In [187]:
mser[:,'u']

w    0.649504
b    0.648698
r    0.972230
dtype: float64

In [192]:
mser.unstack().fillna({'l':'B','r':'R','w':'W'})

d          l         r         u
b  0.580671          B         R  0.648698
r  0.977760  0.0447818         R  0.972230
w  0.703475          B  0.194305  0.649504

In [194]:
frame.stack()

red     ball     -0.247339
        pen       0.062556
        pencil    1.978081
        paper     0.386949
blue    ball      2.308897
        pen       0.721517
        pencil    0.376770
        paper     0.164867
yellow  ball     -0.598208
        pen       0.754422
        pencil    1.160723
        paper     1.836295
white   ball     -0.116154
        pen       1.200319
        pencil   -1.426520
        paper     0.578937
dtype: float64

In [198]:
mframe=pd.DataFrame(np.random.randn(16).reshape(4,4),index=[['w','w','r','r'],['u','d','u','d']],columns=[['p','p','pa','pa'],[1,2,1,2]])

In [199]:
mframe

p                  pa          
            1         2         1         2
w u  0.622461  0.131626 -0.711867 -0.174522
  d  0.791540 -1.281477 -0.305288 -0.930928
r u -0.080492 -1.228205 -0.789417  0.421552
  d -0.615253 -0.689480 -0.344766 -1.342070

In [201]:
mframe.columns.names=['ob','id']
mframe.index.names=['co','st']
mframe

ob            p                  pa          
id            1         2         1         2
co st                                        
w  u   0.622461  0.131626 -0.711867 -0.174522
   d   0.791540 -1.281477 -0.305288 -0.930928
r  u  -0.080492 -1.228205 -0.789417  0.421552
   d  -0.615253 -0.689480 -0.344766 -1.342070

In [203]:
mframe.swaplevel('co','st')

ob            p                  pa          
id            1         2         1         2
st co                                        
u  w   0.622461  0.131626 -0.711867 -0.174522
d  w   0.791540 -1.281477 -0.305288 -0.930928
u  r  -0.080492 -1.228205 -0.789417  0.421552
d  r  -0.615253 -0.689480 -0.344766 -1.342070

In [211]:
mframe.sortlevel('co')

ob            p                  pa          
id            1         2         1         2
co st                                        
r  d  -0.615253 -0.689480 -0.344766 -1.342070
   u  -0.080492 -1.228205 -0.789417  0.421552
w  d   0.791540 -1.281477 -0.305288 -0.930928
   u   0.622461  0.131626 -0.711867 -0.174522

In [212]:
mframe.sum(level='co')

ob         p                  pa          
id         1         2         1         2
co                                        
r  -0.695746 -1.917685 -1.134183 -0.920518
w   1.414002 -1.149850 -1.017155 -1.105450

In [214]:
mframe.sum(level='id',axis=1)

id            1         2
co st                    
w  u  -0.089405 -0.042895
   d   0.486252 -2.212405
r  u  -0.869909 -0.806653
   d  -0.960020 -2.031550