In [1]:
import numpy as np
from pandas import DataFrame,Series
import pandas as pd

In [2]:
frame1=pd.DataFrame({'id':['ball','pencil','pen','mug','ashtray'],'price':[12.33,11.44,33.21,13.23,33.62]})

In [3]:
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [6]:
frame2=pd.DataFrame({'id':['pencil','pencil','ball','pen'],'color':['white','red','red','black']})

In [7]:
frame2

color      id
0  white  pencil
1    red  pencil
2    red    ball
3  black     pen

In [8]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [9]:
frame1=pd.DataFrame({'id':['ball','pencil','pen','mug','ashtray'],'color':['white','red','red','black','green'],'brand':['OMG','ABC','ABC','POD','POD']})

In [10]:
frame1

brand  color       id
0   OMG  white     ball
1   ABC    red   pencil
2   ABC    red      pen
3   POD  black      mug
4   POD  green  ashtray

In [11]:
frame2=pd.DataFrame({'id':['pencil','pencil','ball','pen'],'brand':['OMG','POD','ABC','POD']})

In [12]:
frame2

brand      id
0   OMG  pencil
1   POD  pencil
2   ABC    ball
3   POD     pen

In [13]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [brand, color, id]
Index: []

In [15]:
pd.merge(frame1,frame2,on='brand')

brand  color     id_x    id_y
0   OMG  white     ball  pencil
1   ABC    red   pencil    ball
2   ABC    red      pen    ball
3   POD  black      mug  pencil
4   POD  black      mug     pen
5   POD  green  ashtray  pencil
6   POD  green  ashtray     pen

In [18]:
frame2.columns=['brand','sid']

In [19]:
frame2

brand     sid
0   OMG  pencil
1   POD  pencil
2   ABC    ball
3   POD     pen

In [20]:
pd.merge(frame1,frame2,left_on='id',right_on='sid')

brand_x  color      id brand_y     sid
0     OMG  white    ball     ABC    ball
1     ABC    red  pencil     OMG  pencil
2     ABC    red  pencil     POD  pencil
3     ABC    red     pen     POD     pen

In [26]:
frame2.columns=['brand','id']

In [30]:
pd.merge(frame1,frame2,on='id')

brand_x  color      id brand_y
0     OMG  white    ball     ABC
1     ABC    red  pencil     OMG
2     ABC    red  pencil     POD
3     ABC    red     pen     POD

In [31]:
pd.merge(frame1,frame2,on='id',how='outer')

brand_x  color       id brand_y
0     OMG  white     ball     ABC
1     ABC    red   pencil     OMG
2     ABC    red   pencil     POD
3     ABC    red      pen     POD
4     POD  black      mug     NaN
5     POD  green  ashtray     NaN

In [32]:
pd.merge(frame1,frame2,on='id',how='left')

brand_x  color       id brand_y
0     OMG  white     ball     ABC
1     ABC    red   pencil     OMG
2     ABC    red   pencil     POD
3     ABC    red      pen     POD
4     POD  black      mug     NaN
5     POD  green  ashtray     NaN

In [34]:
pd.merge(frame1,frame2,on='id',how='right')

brand_x  color      id brand_y
0     OMG  white    ball     ABC
1     ABC    red  pencil     OMG
2     ABC    red  pencil     POD
3     ABC    red     pen     POD

In [35]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

brand  color       id
0   OMG  white     ball
1   ABC    red   pencil
2   ABC    red      pen
3   POD  black      mug
4   POD  green  ashtray
5   OMG    NaN   pencil
6   POD    NaN   pencil
7   ABC    NaN     ball
8   POD    NaN      pen

In [37]:
pd.merge(frame1,frame2,right_index=True,left_index=True)

brand_x  color    id_x brand_y    id_y
0     OMG  white    ball     OMG  pencil
1     ABC    red  pencil     POD  pencil
2     ABC    red     pen     ABC    ball
3     POD  black     mug     POD     pen

In [43]:
frame2.columns=['brand2','id2']
frame1.join(frame2)

brand  color       id brand2     id2
0   OMG  white     ball    OMG  pencil
1   ABC    red   pencil    POD  pencil
2   ABC    red      pen    ABC    ball
3   POD  black      mug    POD     pen
4   POD  green  ashtray    NaN     NaN

In [61]:
array1=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [62]:
array2=np.arange(9).reshape(3,3)+6

In [65]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [67]:
np.concatenate([array1,array2],axis=0)#数组连接

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [101]:
ser1=pd.Series(np.random.rand(4),index=[1,2,3,4])
ser1

1    0.659783
2    0.673792
3    0.722075
4    0.135049
dtype: float64

In [118]:
ser2=pd.Series(np.random.randn(4),index=[5,6,7,8])
ser2

5   -0.400405
6   -0.319284
7    0.712139
8   -0.093178
dtype: float64

In [126]:
ser3=pd.concat([ser1,ser2],axis=1)
ser3

0         1
1  0.659783       NaN
2  0.673792       NaN
3  0.722075       NaN
4  0.135049       NaN
5       NaN -0.400405
6       NaN -0.319284
7       NaN  0.712139
8       NaN -0.093178

In [125]:
pd.concat([ser1,ser3],axis=1,join='inner')

0         0   1
1  0.659783  0.659783 NaN
2  0.673792  0.673792 NaN
3  0.722075  0.722075 NaN
4  0.135049  0.135049 NaN

In [134]:
pd.concat([ser1,ser2],keys=[1,2])#创建等级索引

1  1    0.659783
   2    0.673792
   3    0.722075
   4    0.135049
2  5   -0.400405
   6   -0.319284
   7    0.712139
   8   -0.093178
dtype: float64

In [137]:
pd.concat([ser1,ser2],axis=1,keys=[1,2])

1         2
1  0.659783       NaN
2  0.673792       NaN
3  0.722075       NaN
4  0.135049       NaN
5       NaN -0.400405
6       NaN -0.319284
7       NaN  0.712139
8       NaN -0.093178

In [138]:
ser1=pd.Series(np.random.rand(5),index=[1,2,3,4,5])

In [139]:
ser2=pd.Series(np.random.rand(4),index=[2,4,5,6])

In [140]:
ser1,ser2

(1    0.879833
 2    0.680494
 3    0.335538
 4    0.689328
 5    0.191459
 dtype: float64, 2    0.637847
 4    0.203779
 5    0.944177
 6    0.963207
 dtype: float64)

In [149]:
ser1.combine_first(ser2)

1    0.879833
2    0.680494
3    0.335538
4    0.689328
5    0.191459
6    0.963207
dtype: float64

In [151]:
ser2.combine_first(ser1)

1    0.879833
2    0.637847
3    0.335538
4    0.203779
5    0.944177
6    0.963207
dtype: float64

In [157]:
ser1[:3].combine_first(ser2[:3])

1    0.879833
2    0.680494
3    0.335538
4    0.203779
5    0.944177
dtype: float64

In [159]:
frame1=pd.DataFrame(np.arange(9).reshape(3,3),index=['w','b','r'],columns=['ba','pe','pen'])

In [162]:
ser5=frame1.stack()

In [163]:
ser5.unstack()

ba  pe  pen
w   0   1    2
b   3   4    5
r   6   7    8

In [167]:
ser5.unstack(0)

w  b  r
ba   0  3  6
pe   1  4  7
pen  2  5  8

In [181]:
longframe=pd.DataFrame({'color':['w','w','w','r','r','r','b','b','b'],'item':['b','p','m','b','p','m','b','p','m'],'value':np.random.rand(9)})

In [182]:
longframe

color item     value
0     w    b  0.482840
1     w    p  0.934838
2     w    m  0.031912
3     r    b  0.295325
4     r    p  0.178084
5     r    m  0.343522
6     b    b  0.657637
7     b    p  0.564571
8     b    m  0.740072

In [183]:
wideframe=longframe.pivot('color','item')

In [172]:
wideframe

value                    
item          b         m         p
color                              
b      0.094899  0.431285  0.237000
r      0.175936  0.434407  0.579982
w      0.341532  0.859666  0.070030

In [202]:
frame1=pd.DataFrame(np.arange(9).reshape(3,3),index=['w','b','r'],columns=['ball','pen','pencil'])

In [203]:
frame1

ball  pen  pencil
w     0    1       2
b     3    4       5
r     6    7       8

In [204]:
del frame1['ball']#删除原数据

In [205]:
frame1

ball  pen  pencil
w     0    1       2
b     3    4       5
r     6    7       8

In [208]:
frame1.drop('b')#删除视图

ball  pen  pencil
w     0    1       2
r     6    7       8

In [209]:
frame1

ball  pen  pencil
w     0    1       2
b     3    4       5
r     6    7       8

In [210]:
dframe=pd.DataFrame({'color':['w','w','r','r','w'],'value':[2,1,3,3,2]})

In [211]:
dframe

color  value
0     w      2
1     w      1
2     r      3
3     r      3
4     w      2

In [212]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [213]:
frame=pd.DataFrame({'item':['ball','mug','pen','pencil','ashtray'],'color':['white','rosso','verde','black','yellow'],'prece':[5.6,4.3,1.3,0.56,2.75]})

In [214]:
frame

color     item  prece
0   white     ball   5.60
1   rosso      mug   4.30
2   verde      pen   1.30
3   black   pencil   0.56
4  yellow  ashtray   2.75

In [219]:
newcolors={'rosso':'red','verde':'green',1.30:13.0}

In [220]:
newcolors

{1.3: 13.0, 'verde': 'green', 'rosso': 'red'}

In [221]:
frame.replace(newcolors)#替换

color     item  prece
0   white     ball   5.60
1     red      mug   4.30
2   green      pen  13.00
3   black   pencil   0.56
4  yellow  ashtray   2.75

In [222]:
ser=pd.Series([1,3,np.nan,np.nan,4.6,np.nan,3])

In [224]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    0.0
4    4.6
5    0.0
6    3.0
dtype: float64

In [264]:
frame=pd.DataFrame({'item':['ball','mug','pen','pencil','ashtray'],'color':['white','rosso','verde','black','yellow']})

In [265]:
frame

color     item
0   white     ball
1   rosso      mug
2   verde      pen
3   black   pencil
4  yellow  ashtray

In [266]:
price={'ball':5.56,'mug':4.20,'bottle':1.30,'pen':3.14,'pencil':0.56}

In [267]:
frame['price']=frame['item'].map(price)

In [268]:
frame

color     item  price
0   white     ball   5.56
1   rosso      mug   4.20
2   verde      pen   3.14
3   black   pencil   0.56
4  yellow  ashtray    NaN

In [269]:
frame=frame.replace(np.nan,frame['price'].mean())

In [270]:
frame

color     item  price
0   white     ball  5.560
1   rosso      mug  4.200
2   verde      pen  3.140
3   black   pencil  0.560
4  yellow  ashtray  3.365

In [247]:
reindex={0:'first',
             1:'second',
             2:'third',
             3:'fourth'}

In [248]:
reindex

{0: 'first', 1: 'second', 2: 'third', 3: 'fourth'}

In [249]:
frame.rename(reindex)

color     item  price
first    white     ball  5.560
second   rosso      mug  4.200
third    verde      pen  3.140
fourth   black   pencil  0.560
4       yellow  ashtray  3.365

In [250]:
recolumn={'color':1,'item':'x'}

In [261]:
frame.rename(index=reindex,columns=recolumn,inplace=True)#inplace在原数据上改变

In [263]:
frame

1        x  price
first    white     ball  5.560
second   rosso      mug  4.200
third    verde      pen  3.140
fourth   black   pencil  0.560
4       yellow  ashtray  3.365

In [271]:
bins=[0,25,50,75,100]

In [273]:
results=np.arange(100)
cat=pd.cut(results,bins)

In [274]:
cat

[NaN, (0, 25], (0, 25], (0, 25], (0, 25], ..., (75, 100], (75, 100], (75, 100], (75, 100], (75, 100]]
Length: 100
Categories (4, object): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [275]:
cat.levels

/root/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
  if __name__ == '__main__':


Index(['(0, 25]', '(25, 50]', '(50, 75]', '(75, 100]'], dtype='object')

In [276]:
cat.labels

/root/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  if __name__ == '__main__':


array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3], dtype=int8)

In [277]:
pd.value_counts(cat)

(50, 75]     25
(25, 50]     25
(0, 25]      25
(75, 100]    24
dtype: int64

In [278]:
bin_name=['a','b','c','d']

In [280]:
pd.cut(results,bins,labels=bin_name)

[NaN, a, a, a, a, ..., d, d, d, d, d]
Length: 100
Categories (4, object): [a < b < c < d]

In [282]:
pd.cut(results,5)

[(-0.099, 19.8], (-0.099, 19.8], (-0.099, 19.8], (-0.099, 19.8], (-0.099, 19.8], ..., (79.2, 99], (79.2, 99], (79.2, 99], (79.2, 99], (79.2, 99]]
Length: 100
Categories (5, object): [(-0.099, 19.8] < (19.8, 39.6] < (39.6, 59.4] < (59.4, 79.2] < (79.2, 99]]

In [283]:
pd.qcut(results,5)

[[0, 19.8], [0, 19.8], [0, 19.8], [0, 19.8], [0, 19.8], ..., (79.2, 99], (79.2, 99], (79.2, 99], (79.2, 99], (79.2, 99]]
Length: 100
Categories (5, object): [[0, 19.8] < (19.8, 39.6] < (39.6, 59.4] < (59.4, 79.2] < (79.2, 99]]

In [284]:
pd.value_counts(pd.qcut(results,5))

(79.2, 99]      20
(59.4, 79.2]    20
(39.6, 59.4]    20
(19.8, 39.6]    20
[0, 19.8]       20
dtype: int64

In [285]:
randframe=pd.DataFrame(np.random.randn(1000,3))

In [286]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.010851    -0.009178     0.014033
std       1.020114     0.996585     0.987941
min      -3.496654    -3.670713    -3.076952
25%      -0.686316    -0.693537    -0.638661
50%      -0.005490    -0.025159     0.027524
75%       0.727263     0.691062     0.727501
max       3.340003     3.299846     2.778750

In [290]:
randframe[(np.abs(randframe)>(3*randframe.std())).any(1)]#借助any(1)可以对每列筛选

0         1         2
95   3.340003 -1.988956  1.905893
196 -0.026537 -3.670713 -1.206426
263  0.363244  3.299846  0.587883
282 -3.496654  1.142483 -2.034188
647  1.087430  0.562111 -3.076952
686 -3.078354 -0.328011  0.903857

In [292]:
nframe=pd.DataFrame(np.arange(25).reshape(5,5)+1)
nframe

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [298]:
new_order=np.random.permutation(5)

In [299]:
new_order

array([3, 1, 2, 4, 0])

In [301]:
nframe.take(new_order)#按照指定次序索引排序

0   1   2   3   4
3  16  17  18  19  20
1   6   7   8   9  10
2  11  12  13  14  15
4  21  22  23  24  25
0   1   2   3   4   5

In [302]:
new_order=[3,4,2]

In [303]:
nframe.take(new_order)

0   1   2   3   4
3  16  17  18  19  20
4  21  22  23  24  25
2  11  12  13  14  15

In [304]:
sample=np.random.randint(0,len(nframe),size=3)

In [305]:
sample

array([3, 2, 3])

In [307]:
np.random.randint(1,30,size=10)

array([ 7, 15, 16, 19, 23,  7, 28, 16,  5, 16])

In [308]:
text='16 Bolton Avenue , Boston'

In [315]:
a=text.split(',')#不会去掉空格

In [316]:
tokens=[s.strip() for s in text.split(',')] #去掉空格

In [313]:
tokens

['16 Bolton Avenue', 'Boston']

In [320]:
a[0].strip()

'16 Bolton Avenue'

In [321]:
adders,city=[s.strip() for s in text.split(',')]

In [324]:
adders,city

('16 Bolton Avenue', 'Boston')

In [328]:
adders+' , '+city

'16 Bolton Avenue , Boston'

In [329]:
strings=['A+','A','A-','B','BB','BBB','C+']

In [332]:
'####'.join(strings)

'A+####A####A-####B####BB####BBB####C+'

# 正则表达式

In [333]:
import re

In [334]:
text="This is        an\t odd  \n  text!"

In [344]:
re.split('\s+',text)

['This', 'is', 'an', 'odd', 'text!']

In [347]:
regex=re.compile('\s+')#编译正则表达式

In [348]:
regex.split(text)

['This', 'is', 'an', 'odd', 'text!']

In [349]:
text="This is mu address: 16 Bolton Avenue, Boston"

In [353]:
re.findall('A\w+',text)

['Avenue']

In [354]:
re.findall('[A,a]\w+',text)

['address', 'Avenue']

In [355]:
re.search('[A,a]\w+',text)

<_sre.SRE_Match object; span=(11, 18), match='address'>

In [356]:
reg=re.search('[A,a]\w+',text)

In [357]:
reg.start()

11

In [358]:
reg.end()

18

In [360]:
text[reg.start():reg.end()]

'address'

In [361]:
re.match('T\w+',text)

<_sre.SRE_Match object; span=(0, 4), match='This'>

In [365]:
mat=re.match('A\w+',text)#只查找第一个字符串

# 分组

In [368]:
frame=pd.DataFrame({'color':['white','red','green','red','green'],
                                   'object':['pen','pencil','pencil','ashtray','pen'],
                                    'price1':[5.6,4.2,1.3,0.56,2.75],
                                    'price2':[4.7,4.21,1.6,0.75,3.15]})

In [369]:
frame

color   object  price1  price2
0  white      pen    5.60    4.70
1    red   pencil    4.20    4.21
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [376]:
group=frame['price1'].groupby(frame['color'])

In [377]:
group.groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [378]:
group.mean()

color
green    2.025
red      2.380
white    5.600
Name: price1, dtype: float64

In [379]:
group.sum()

color
green    4.05
red      4.76
white    5.60
Name: price1, dtype: float64

In [380]:
ggroup=frame['price1'].groupby([frame['color'],frame['object']])

In [381]:
ggroup.groups

{('green', 'pen'): [4],
 ('green', 'pencil'): [2],
 ('red', 'ashtray'): [3],
 ('red', 'pencil'): [1],
 ('white', 'pen'): [0]}

In [382]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.60
Name: price1, dtype: float64

In [383]:
frame[['price1','price2']].groupby(frame['color']).mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.480
white   5.600   4.700

In [387]:
for name,group in frame.groupby('color'):
    print(name)
    print(group)

green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.21
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen     5.6     4.7


In [388]:
means=frame.groupby(frame['color']).mean().add_prefix('mean_')

In [389]:
means

mean_price1  mean_price2
color                          
green        2.025        2.375
red          2.380        2.480
white        5.600        4.700

In [390]:
group=frame.groupby('color')

In [396]:
group['price1'].quantile(0.1)#计算分位数

color
green    1.445
red      0.924
white    5.600
Name: price1, dtype: float64

In [403]:
def range1(i):
    return i.max()-i.min()

In [404]:
group['price1'].agg(range1)

color
green    1.45
red      3.64
white    0.00
Name: price1, dtype: float64

In [405]:
group.agg(range1)

price1  price2
color                
green    1.45    1.55
red      3.64    3.46
white    0.00    0.00

In [407]:
group.agg(['mean','std',range1])

price1                  price2                 
        mean       std range1   mean       std range1
color                                                
green  2.025  1.025305   1.45  2.375  1.096016   1.55
red    2.380  2.573869   3.64  2.480  2.446589   3.46
white  5.600       NaN   0.00  4.700       NaN   0.00

In [408]:
frame=pd.DataFrame({'color':['w','r','g','r','g'],'price1':[5.6,4.2,1.3,0.56,2.75],'price2':[4.75,4.12,1.60,0.75,3.15]})

In [409]:
frame

color  price1  price2
0     w    5.60    4.75
1     r    4.20    4.12
2     g    1.30    1.60
3     r    0.56    0.75
4     g    2.75    3.15

In [412]:
sums=frame.groupby('color').sum().add_prefix('tot_')
sums

tot_price1  tot_price2
color                        
g            4.05        4.75
r            4.76        4.87
w            5.60        4.75

In [414]:
pd.merge(frame,sums,left_on='color',right_index=True)

color  price1  price2  tot_price1  tot_price2
0     w    5.60    4.75        5.60        4.75
1     r    4.20    4.12        4.76        4.87
3     r    0.56    0.75        4.76        4.87
2     g    1.30    1.60        4.05        4.75
4     g    2.75    3.15        4.05        4.75

In [416]:
frame.groupby('color').transform(np.sum).add_prefix('tot_')

tot_price1  tot_price2
0        5.60        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75

In [417]:
frame=DataFrame({'color':['white','black','white','white','black','black'],
                 'status':['up','up','down','down','down','up'],
                 'value1':[12.33,14.55,22.34,27.84,23.40,18.33],
                 'value2':[11.23,31.80,29.99,31.81,18.25,22.44]})
                 

In [418]:
frame

color status  value1  value2
0  white     up   12.33   11.23
1  black     up   14.55   31.80
2  white   down   22.34   29.99
3  white   down   27.84   31.81
4  black   down   23.40   18.25
5  black     up   18.33   22.44

In [419]:
frame.groupby(['color','status']).apply(lambda x: x.max())

color status  value1  value2
color status                              
black down    black   down   23.40   18.25
      up      black     up   18.33   31.80
white down    white   down   27.84   31.81
      up      white     up   12.33   11.23

In [422]:
frame.groupby(['status','color']).apply(lambda x: x.max())

color status  value1  value2
status color                              
down   black  black   down   23.40   18.25
       white  white   down   27.84   31.81
up     black  black     up   18.33   31.80
       white  white     up   12.33   11.23