In [103]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

In [3]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [4]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [5]:
df2 = DataFrame({'key':['a','b','d'],'data2':range(3)})

In [6]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [10]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [11]:
pd.merge(df1,df2,on = 'key')#

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [19]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})

In [20]:
df4 = DataFrame({'rkey':['a','b','d'],'data2':range(3)})

In [22]:
pd.merge(df4,df3,left_on='rkey',right_on='lkey')#默认merge是inner连接，

data2 rkey  data1 lkey
0      0    a      2    a
1      0    a      4    a
2      0    a      5    a
3      1    b      0    b
4      1    b      1    b
5      1    b      6    b

In [ ]:
pd.merge(df1,df2,how='outer')

In [34]:
df1=DataFrame({'key':list('bbacab'),'data1':range(6)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [31]:
df2 = DataFrame({'key':list('ababd'),'data2':range(5)})
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [35]:
pd.merge(df1,df2,on='key',how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [36]:
pd.merge(df1,df2,on='key',how='inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [46]:
left=DataFrame({'key1':['foo','foo','bar'],'key2':['one','one','two'],'rval1':[1,2,3]})

In [47]:
left

key1 key2  rval1
0  foo  one      1
1  foo  one      2
2  bar  two      3

In [48]:
right=DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'rval2':[4,5,6,7]})

In [49]:
right

key1 key2  rval2
0  foo  one      4
1  foo  one      5
2  bar  one      6
3  bar  two      7

In [50]:
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  rval1  rval2
0  foo  one    1.0      4
1  foo  one    1.0      5
2  foo  one    2.0      4
3  foo  one    2.0      5
4  bar  two    3.0      7
5  bar  one    NaN      6

In [51]:
pd.merge(left,right,on='key1')

key1 key2_x  rval1 key2_y  rval2
0  foo    one      1    one      4
1  foo    one      1    one      5
2  foo    one      2    one      4
3  foo    one      2    one      5
4  bar    two      3    one      6
5  bar    two      3    two      7

In [52]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  rval1 key2_right  rval2
0  foo       one      1        one      4
1  foo       one      1        one      5
2  foo       one      2        one      4
3  foo       one      2        one      5
4  bar       two      3        one      6
5  bar       two      3        two      7

In [57]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [59]:
right1 = DataFrame({'group_val':[3.5,7]},index=['a','b'])
right

group_val
a        3.5
b        7.0

In [60]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [61]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [69]:
lefth = DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],'key2':[2000,2001,2002,2001,2002],'data':np.arange(5)})
lefth

data    key1  key2
0     0    Ohio  2000
1     1    Ohio  2001
2     2    Ohio  2002
3     3  Nevada  2001
4     4  Nevada  2002

In [67]:
righth = DataFrame(np.arange(12).reshape((6,2)),index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],[2001,2000,2000,2000,2001,2002]],columns=['event1','event2'])

In [68]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [77]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True)#how='inner')

data    key1  key2  event1  event2
0     0    Ohio  2000       4       5
0     0    Ohio  2000       6       7
1     1    Ohio  2001       8       9
2     2    Ohio  2002      10      11
3     3  Nevada  2001       0       1

In [78]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True,how='outer')

data    key1    key2  event1  event2
0   0.0    Ohio  2000.0     4.0     5.0
0   0.0    Ohio  2000.0     6.0     7.0
1   1.0    Ohio  2001.0     8.0     9.0
2   2.0    Ohio  2002.0    10.0    11.0
3   3.0  Nevada  2001.0     0.0     1.0
4   4.0  Nevada  2002.0     NaN     NaN
4   NaN  Nevada  2000.0     2.0     3.0

In [79]:
left2 = DataFrame([[1,2],[3,4],[5,6]],index=['a','c','e'],columns=['Ohio','Nevada'])

In [80]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [82]:
right2 = DataFrame([[7,8],[9,10],[11,12],[13,14]],index=list('bcde'),columns=['Missouri','Alabama'])

In [83]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [84]:
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [86]:
left2.join(right2,how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [87]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [92]:
another=DataFrame([[7,8],[9,10],[11,12],[16,17]],index=list('acef'),columns=['New York','Oregon'])

In [93]:
another

New York  Oregon
a         7       8
c         9      10
e        11      12
f        16      17

In [97]:
left2.join([right2,another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2       NaN      NaN         7       8
c     3       4       9.0     10.0         9      10
e     5       6      13.0     14.0        11      12

In [96]:
left2.join([right2,another],how='outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

In [107]:
arr = np.arange(12).reshape((3,4))

In [108]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [118]:
s1=Series([0,1],index=['a','b'])
s1

a    0
b    1
dtype: int64

In [119]:
s2=Series([2,3,4],index=['c','d','e'])
s2

c    2
d    3
e    4
dtype: int64

In [120]:
s3=Series([5,6],index=['f','g'])
s3

f    5
g    6
dtype: int64

In [125]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [128]:
s4 = pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [129]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [131]:
result=pd.concat([s1,s1,s3],keys=['one','two','three'])

In [132]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [137]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [136]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [138]:
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [139]:
pd.concat([s1,s2,s3],axis=0,keys=['one','two','three'])

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [144]:
df1=DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])

In [145]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [152]:
df2=DataFrame(np.arange(4).reshape(2,2)+5,index=['a','c'],columns=['three','four'])

In [153]:
df2

three  four
a      5     6
c      7     8

In [154]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [155]:
pd.concat([df1,df2],axis=0,keys=['level1','level2'])

four  one  three  two
level1 a   NaN  0.0    NaN  1.0
       b   NaN  2.0    NaN  3.0
       c   NaN  4.0    NaN  5.0
level2 a   6.0  NaN    5.0  NaN
       c   8.0  NaN    7.0  NaN

In [159]:
pd.concat({'level1':df1,'level2':df2},axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [160]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],names=['upper','lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [161]:
df1 = DataFrame(np.random.randn(3,4),columns=list('abcd'))

In [162]:
df1

a         b         c         d
0  0.009486 -0.954538  1.394457  0.685374
1  0.298968 -2.197838  0.301884  0.257931
2  1.591111 -1.069119 -0.697512 -1.142861

In [163]:
df2 = DataFrame(np.random.randn(2,3),columns=['b','d','a'])

In [164]:
df2

b         d         a
0  0.355685  1.682081 -1.181945
1  0.155360  0.382529 -0.952000

In [165]:
pd.concat([df1,df2],ignore_index=True)

a         b         c         d
0  0.009486 -0.954538  1.394457  0.685374
1  0.298968 -2.197838  0.301884  0.257931
2  1.591111 -1.069119 -0.697512 -1.142861
3 -1.181945  0.355685       NaN  1.682081
4 -0.952000  0.155360       NaN  0.382529

In [169]:
a=Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [172]:
b=Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [173]:
b[-1] = np.nan

In [174]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [175]:
np.where(pd.isnull(a),b,a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [185]:
a[:].combine_first(b[:])#先a如果没有则取b

f    0.0
e    2.5
d    2.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [188]:
df1=DataFrame({'a':[1,np.nan,5,np.nan],'b':[np.nan,2,np.nan,6],'c':range(2,18,4)})

In [189]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [190]:
df2 = DataFrame({'a':[5,4,np.nan,3,7],'b':[np.nan,3,4,6,8]})

In [191]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [192]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [193]:
data = DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['Ohio','Colorado'],name='state'),columns=pd.Index(['oen','two','three'],name='number'))

In [194]:
data

number    oen  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [199]:
result = data.stack()
result

state     number
Ohio      oen       0
          two       1
          three     2
Colorado  oen       3
          two       4
          three     5
dtype: int32

In [203]:
result.unstack()

number    oen  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [210]:
result.unstack(1)

number    oen  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [205]:
result.unstack('state')

state   Ohio  Colorado
number                
oen        0         3
two        1         4
three      2         5

In [212]:
result.unstack()

number    oen  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [214]:
s1 = Series([0,1,2,3],index=['a','b','c','d'])
s1

a    0
b    1
c    2
d    3
dtype: int64

In [215]:
s2 = Series([4,5,6],index=['c','d','e'])

In [216]:
s2

c    4
d    5
e    6
dtype: int64

In [220]:
data2=pd.concat([s1,s2],keys=['one','two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [221]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0