In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
vectorizer = CountVectorizer(min_df=1)

In [11]:
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [33]:
content=["How to format my hard disk","Hard disk format problems"]

In [34]:
x=vectorizer.fit_transform(content)

In [35]:
x

<2x7 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [36]:
vectorizer.get_feature_names()

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']

In [37]:
x.toarray().transpose()

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0]], dtype=int64)

In [38]:
x.toarray()

array([[1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [58]:
import os
DIR='C:/Users/Z/Desktop/新建文件夹/2CPTJ/'
posts=[open(os.path.join(DIR,f)).read() for f in os.listdir(DIR)]

In [59]:
posts

['This is a toy post about machine learning.Actually,it contains not much interesting stuff.',
 'Imaging databases can get huge',
 'Most imaging databases safe images permanently.',
 'Imaging database store images.\n',
 'Imaging databases store images.Imaging databases store imaging.Imaging databases store images.']

In [60]:
x_train=vectorizer.fit_transform(posts)

In [61]:
num_samples,num_features=x_train.shape

In [62]:
print("#samples:%d, #features: %d"%(num_samples,num_features))

#samples:5, #features: 25


In [63]:
vectorizer.get_feature_names()

['about',
 'actually',
 'can',
 'contains',
 'database',
 'databases',
 'get',
 'huge',
 'images',
 'imaging',
 'interesting',
 'is',
 'it',
 'learning',
 'machine',
 'most',
 'much',
 'not',
 'permanently',
 'post',
 'safe',
 'store',
 'stuff',
 'this',
 'toy']

In [64]:
x_train.toarray().transpose()

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 1, 0, 3],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 2],
       [0, 1, 1, 1, 4],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 3],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=int64)

In [66]:
new_post="imaging databases"

In [67]:
new_post_vec=vectorizer.transform([new_post])

In [72]:
print(new_post_vec.toarray())

[[0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [71]:
new_post_vec

<1x25 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [73]:
import scipy as sp
def dist_raw(v1,v2):
    delta=v1-v2
    return sp.linalg.norm(delta.toarray())

In [79]:
import sys
best_doc=None
#best_dist=sys.maxint
best_i=None
for i in range(0,num_samples):
    post = posts[i]
    if post==new_post:
        continue
    post_vec = x_train.getrow(i)
    d=dist_raw(post_vec,new_post_vec)
    print("===Post %i with dist=%.2f: %s"%(i,d,post))
    if d<best_dist:
        best_dist = d
        best_i = i

===Post 0 with dist=4.00: This is a toy post about machine learning.Actually,it contains not much interesting stuff.


NameError: name 'best_dist' is not defined